### ISSUE TITLE
undefined method `to_string' errors in /user_events search

### ISSUE THREAD

**Issue by RaisingK** [danbooru/danbooru#4868]
https://danbooru.donmai.us/user_events?search%5Buser_session%5D%5Bip_geolocation%5D%5Bcountry%5D=US and https://danbooru.donmai.us/user_events?search%5Buser_session%5D%5Bip_geolocation%5D%5Bcity%5D=Enterprise produce:

    undefined method to_string for "[...]/[...]":String Did you mean? to_str

    NoMethodError exception raised
    app/logical/ip_address_type.rb:19:in `serialize'
    app/logical/pagination_extension.rb:137:in `records'
    app/views/table_builder/_table.html.erb:13:in `each_with_index'
    app/views/table_builder/_table.html.erb:13
    app/views/table_builder/_table.html.erb:1
    app/helpers/application_helper.rb:252:in `table_for'
    app/views/user_events/index.html.erb:18
    app/controllers/application_controller.rb:42:in `respond_with'
    app/controllers/user_events_controller.rb:8:in `index'

**Comment by nonamethanks** [comment]
Wonder if this has been caused by the pundit update too, like issue #4867.

**Comment by evazion** [comment]
This looks like a Rails bug. I bisected it to being introduced in https://github.com/rails/rails/commit/4b1122c572060e9a2a344608b15dfcbb7ff82213.
